---
# tasks file for conner.pythonenv
- name: Install WebApp Libs and Git
  apt:
    name: "{{ item }}"
    state: latest
  with_items:
     - python
     - python-dev
     - python-virtualenv
     - git
     - gcc
~
